### ISSUE TITLE
This would be awesome PR to merge.

### ISSUE THREAD

**Issue by YaowamalSomthai** [YaowamalSomthai/mint2#1]
This would be awesome PR to merge. 

As a workaround until this gets merged, you can do this: 
```shell
kubectl config set clusters.$EKS_CLUSTER_ARN.proxy-url $PROXY_URL
```
So given the following kube config file: 
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://....eks.amazonaws.com
  name: arn:aws:eks:...:cluster/some_name
...
```
the following command will create a `proxy-url` in it pointing to `socks5://localhost:1099`: 
```shell
kubectl config set clusters.arn:aws:eks:...:cluster/some_name.proxy-url socks5://localhost:1099
```

_Originally posted by @schollii in https://github.com/aws/aws-cli/issues/7622#issuecomment-1465248943_
